routes/web.php
<?php

use App\Http\Controllers\Admin\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::middleware('admin')->group(function () {
    Route::resource('product', ProductController::class);
});

require __DIR__ . '/auth.php';

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'title',
        'price',
        'description',
    ];

    public function users(): BelongsToMany
    {
        return $this->BelongsToMany(User::class)->withTimestamps();
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/API/AuthController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Http\Requests\Api\LoginRequest;
use App\Http\Requests\Api\RegisterRequest;
use App\Models\User;
use Illuminate\Support\Facades\Auth;

class AuthController extends Controller
{
    public function register(RegisterRequest $request)
    {
        $user = User::create($request->validated());
        $access_token = $user->createToken('auth_token')->accessToken;

        return $this->return_success(['user_token' => $access_token]);
    }

    public function login(LoginRequest $request)
    {
        if ($request->email && Auth::attempt($request->only('email', 'password'))) {
            $user = Auth::user();

            $access_token = $user->createToken('auth_token')->accessToken;

            return $this->return_success(['user_token' => $access_token]);
        } else {
            return $this->return_fail_message(trans('auth.failed'));
        }
    }

    public function logout()
    {
        $user = auth()->user();
        $user->tokens()->delete();

        return $this->return_success();
    }

}

app/Http/Controllers/API/ProductController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Http\Resources\ProductResource;
use App\Models\Product;

class ProductController extends Controller
{
    public function index()
    {
        $products = Product::orderBy('price')->get();
        return $this->return_success(ProductResource::collection($products));
    }

    public function follow(Product $product)
    {
        $product->users()->attach([auth()->id()]);
        return $this->return_success();
    }

    public function unfollow(Product $product)
    {
        $product->users()->detach([auth()->id()]);
        return $this->return_success();
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Web\ProductRequest;
use App\Models\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $items = Product::get();
        return view('admin-panel.product.product-lists', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $form_title = 'Добавить продукт';
        $action_url = route('product.store');

        return view('admin-panel.product.product-form', compact('form_title', 'action_url'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(ProductRequest $request)
    {
        $valid_data = $request->validated();
        Product::create($valid_data);

        return redirect()->route('product.index');
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Product $product)
    {
        $form_title = 'Редактировать продукт';
        $action_url = route('product.update', ['product' => $product->id]);

        return view('admin-panel.product.product-form', compact('form_title', 'action_url', 'product'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Product $product)
    {
        $valid_data = $request->validate([
            'price' => 'required|numeric'
        ]);
        $product->update($valid_data);

        return redirect()->route('product.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Product $product)
    {
        $product->delete();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Http\JsonResponse;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;

    protected function return_success($data = null, $additional = []): JsonResponse
    {
        return response()->json(['success' => true, 'data' => $data] + $additional, 200);
    }

    protected function return_fail_message($message = null): JsonResponse
    {
        return response()->json(['success' => false, 'message' => $message], 200);
    }
}

resources/views/admin-panel/product/product-form.blade.php
@push('styles')
    <style>
        .dd-option-image,
        .dd-selected-image {
            width: 2em;
        }
    </style>
@endpush

<x-admin-panel.layouts.app>
    <div class="row">
        <div class="col-xxl-12">

            <x-admin-panel.layouts.error-list />

            <div class="card">
                <div class="card-header align-items-center d-flex">
                    <h4 class="card-title mb-0 flex-grow-1">{{ $form_title }}</h4>
                </div>
                <div class="card-body">
                    <div class="live-preview">
                        <form action="{{ $action_url }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @isset($product)
                                @method('PUT')
                            @endisset
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <x-admin-panel.forms.text-input name="title" type="text" label="Название"
                                            value="{{ $product->title ?? null }}" />
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <x-admin-panel.forms.text-input name="price" type="number"
                                            label="Цена" value="{{ $product->price ?? null }}" />
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <x-admin-panel.forms.textarea name="description" label="Описание">
                                            {{ $product->description ?? null }}
                                        </x-admin-panel.forms.textarea>
                                    </div>
                                </div>

                                <div class="text-end">
                                    <a href="{{ route('product.index') }}" class="btn btn-danger">Назад</a>
                                    <button type="submit" class="btn btn-primary">Сохранить</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div><!-- end card-body -->
            </div><!-- end card -->
        </div>
        <!--end col-->
    </div>
</x-admin-panel.layouts.app>

resources/views/admin-panel/product/product-lists.blade.php
@push('styles')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.9/css/responsive.bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.2.2/css/buttons.dataTables.min.css">
@endpush

@push('scripts')
    <!--datatable js-->
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js"></script>

    <script>
        $(document).ready(function() {
            $('#example').DataTable({
                "order": [],
                "language": {
                    url: '//cdn.datatables.net/plug-ins/1.13.4/i18n/ru.json',
                },
                "columnDefs": [{
                        "width": "15%",
                        "orderable": false,
                        "targets": -1
                    },
                    {
                        "width": "5%",
                        "targets": 0
                    }
                ]
            });
        });
    </script>
@endpush

<x-admin-panel.layouts.app>
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header d-flex align-items-center">
                    <h5 class="card-title mb-0 flex-grow-1">Продукты</h5>
                    <div>
                        <a href="{{ route('product.create') }}" class="btn btn-primary">Добавить</a>
                    </div>
                </div>
                <div class="card-body">
                    <table id="example" class="table table-bordered dt-responsive nowrap table-striped align-middle"
                        style="width:100%">
                        <thead>
                            <tr>
                                <th>№</th>
                                <th>Название</th>
                                <th>Цена</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($items as $item)
                                <tr>
                                    <td>{{ $item->id }}</td>
                                    <td>{{ $item->title }}</td>
                                    <td>{{ $item->price }}</td>
                                    <td>
                                        <a href="{{ route('product.edit', ['product' => $item->id]) }}"
                                            class="btn btn-sm btn-soft-info">Редактировать</a>
                                        <button class="btn btn-sm btn-soft-danger show-delete-item-modal"
                                            data-bs-toggle="modal" data-bs-target=".delete-modal"
                                            data-url="{{ route('product.destroy', ['product' => $item->id]) }}">Удалить</button>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!--end col-->
    </div>
    <!--end row-->
</x-admin-panel.layouts.app>